spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  jwt:
    secret: ${JWT_SECRET}
    access-token-expired-ms: 3600000 # 1시간
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET}
      region:
        # asia-pacific 북동쪽 2번은 우리나라. 1번이 일본임
        static: ${S3_REGION}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      stack:
        auto: false

  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30분
  jpa:
    hibernate:
      # ddl-auto: update # 기존 더미 데이터 삭제되지 않게
      ddl-auto: create # 매번 db 초기화하고 시작
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org.hibernate.SQL: DEBUG
  main:
    allow-bean-definition-overriding: true
springdoc:
  show-login-endpoint: true