name: CD to EC2

# master 브랜치로 push 되었을때 해당 workflow 를 실행시켜라
on:
  push:
    branches:
      - master

jobs:
  Deploy:
    # jobs 실행 환경 필수적으로 명시해야함
    # ubuntu OS 에서 실행시키는 작업이다~
    runs-on: ubuntu-latest
    steps:
      - name: Access EC2 by SSH Key
        uses: appleboy/ssh-action@v1.0.3
        with:

          # workflow 가 실행될때 Github Secrets 에 설정된 값을 참조해서 동적으로 스크립트를 완성시키고 실행시킴
          host: ${{ secrets.EC2_HOST }} # EC2 IP 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 사용자 이름
          key: ${{ secrets.EC2_PRIVATE_KEY }} # EC2 KEY

          script_stop: true
          # 1. EC2에서 프로젝트 경로로 이동
          # 2. EC2에서 pull 실행
          # 3. build 해서 .jar 파일 다시 만들어주기
          # 4. 기존에 8080 포트로 올라간 것을 꺼주거나, 서버가 안올라가 있을 경우에는 앞에꺼가 false 가 뜨므로 안올라가 있을떄는 무조건 true 되게 하기
          # 5. 백그라운드로 돌리기 위해 nohup 쓰고 SNAPSHOT.jar 파일을 실행시키기 (로그는 콘솔창이 아닌 output.log 에 기록. 덮어씌워짐)
          # 6. github cache 파일 모두 삭제하기

          # 최소 힙 70MB 최대 80MB로 설정
          script: |
            cd /home/ubuntu/pinterest
            
            git pull origin master
            
            touch .env
            echo "${{ secrets.ENV_FILE }}" > .env
            
            chmod +x ./gradlew
            ./gradlew clean build
            
            sudo fuser -k -n tcp 8081 || true
            nohup java -Xms70m -Xmx80m -jar build/libs/*SNAPSHOT.jar > ./server.log 2>&1 &